workflows:
  android-preview:
    name: Android Preview Build (APK)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      # 如果需要环境变量组，取消下面的注释并添加组名
      # groups:
      #   - your_group_name
      vars:
        EXPO_PUBLIC_API_KEY: $EXPO_PUBLIC_API_KEY
      node: 20.18.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Setup Expo
        script: |
          npx expo install --fix
      - name: Prebuild (if needed)
        script: |
          npx expo prebuild --platform android --clean || true
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - epitomizelu@gmail.com
        notify:
          success: true
          failure: true

  android-production:
    name: Android Production Build (AAB)
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      # 如果需要环境变量组，取消下面的注释并添加组名
      # groups:
      #   - your_group_name
      vars:
        EXPO_PUBLIC_API_KEY: $EXPO_PUBLIC_API_KEY
      node: 20.18.0
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Setup Expo
        script: |
          npx expo install --fix
      - name: Prebuild (if needed)
        script: |
          npx expo prebuild --platform android --clean || true
      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - epitomizelu@gmail.com # 替换为你的邮箱
        notify:
          success: true
          failure: true

