/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/p-confirm_dialog`; params?: Router.UnknownInputParams; } | { pathname: `/p-data_view`; params?: Router.UnknownInputParams; } | { pathname: `/p-export_success`; params?: Router.UnknownInputParams; } | { pathname: `/p-home`; params?: Router.UnknownInputParams; } | { pathname: `/p-login`; params?: Router.UnknownInputParams; } | { pathname: `/p-report_view`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/p-confirm_dialog`; params?: Router.UnknownOutputParams; } | { pathname: `/p-data_view`; params?: Router.UnknownOutputParams; } | { pathname: `/p-export_success`; params?: Router.UnknownOutputParams; } | { pathname: `/p-home`; params?: Router.UnknownOutputParams; } | { pathname: `/p-login`; params?: Router.UnknownOutputParams; } | { pathname: `/p-report_view`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/p-confirm_dialog${`?${string}` | `#${string}` | ''}` | `/p-data_view${`?${string}` | `#${string}` | ''}` | `/p-export_success${`?${string}` | `#${string}` | ''}` | `/p-home${`?${string}` | `#${string}` | ''}` | `/p-login${`?${string}` | `#${string}` | ''}` | `/p-report_view${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/p-confirm_dialog`; params?: Router.UnknownInputParams; } | { pathname: `/p-data_view`; params?: Router.UnknownInputParams; } | { pathname: `/p-export_success`; params?: Router.UnknownInputParams; } | { pathname: `/p-home`; params?: Router.UnknownInputParams; } | { pathname: `/p-login`; params?: Router.UnknownInputParams; } | { pathname: `/p-report_view`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
